import { Geist, Geist_Mono } from "next/font/google";
import "../styles/main.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Layout({ children }) 
{  return <div className="bg-orange-400">{children}</div>;}
  
 export default Layout;

